INSERT INTO dog (id, name, Breed, origin) VALUES (1, 'Cheique','Border Collie', 'Casa dos Pais');
INSERT INTO dog (id, name, Breed, origin) VALUES (2, 'Manu','Shih-tzu', 'Minha Casa');
INSERT INTO dog (id, name, Breed, origin) VALUES (3, 'Spuleta','Shih-tzu', 'Minha Casa');
INSERT INTO dog (id, name, Breed, origin) VALUES (4, 'Amora','Shih-tzu', 'Minha da Sogra');
INSERT INTO dog (id, name, Breed, origin) VALUES (5, 'Milly','Yorkshire', 'Casa da Irmã');
INSERT INTO dog (id, name, breed, origin) VALUES (11, 'Fluffy', 'Pomeranian', 'Mountain View, CA');
INSERT INTO dog (id, name, breed, origin) VALUES (12, 'Spot', 'Pit Bull', 'Austin, TX');
INSERT INTO dog (id, name, breed, origin) VALUES (13, 'Ginger', 'Cocker Spaniel', 'Kansas City, KS');
INSERT INTO dog (id, name, breed, origin) VALUES (14, 'Lady', 'Direwolf', 'The North');
INSERT INTO dog (id, name, breed, origin) VALUES (15, 'Sasha', 'Husky', 'Buffalo, NY');